<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>table_fixcontains_fix</name>
   <tag></tag>
   <elementGuidId>b6bd6522-d051-4f85-867f-6a11c5ae61c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@testid='urm-table']/div/table/tbody/tr/td[7]/span[contains(text(),'(черновик)')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@testid='urm-table']/div/table/tbody/tr/td[7]/span[contains(text(),'(черновик)')]</value>
   </webElementProperties>
</WebElementEntity>
